name: Backend test coverage

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: npm test

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Check minimum test coverage percentage
        run: |
          pct=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          echo "Current test coverage: $pct"
          if (( pct < 150 )); then
            echo "Test coverage is less than 150%"
            exit 1
      
      - name: Final List  files in the repository
        run: |
            ls ${{ github.workspace }}

